# Generated by Django 6.0 on 2025-12-07 23:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDAResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('summary_stats', models.JSONField(blank=True, default=dict)),
                ('distributions', models.JSONField(blank=True, default=dict)),
                ('correlation_matrix', models.JSONField(blank=True, default=dict)),
                ('top_correlations', models.JSONField(blank=True, default=list)),
                ('missing_analysis', models.JSONField(blank=True, default=dict)),
                ('outlier_analysis', models.JSONField(blank=True, default=dict)),
                ('insights', models.JSONField(blank=True, default=list)),
                ('ai_insights', models.TextField(blank=True, default='')),
                ('sampled', models.BooleanField(default=False, help_text='Whether the EDA was performed on a sample')),
                ('sample_size', models.PositiveIntegerField(blank=True, help_text='Number of rows in the sample', null=True)),
                ('computation_time', models.FloatField(blank=True, help_text='Time taken for computation in seconds', null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eda_results', to='datasets.dataset')),
            ],
            options={
                'db_table': 'eda_results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dataset', '-created_at'], name='eda_results_dataset_fc0a48_idx'), models.Index(fields=['status'], name='eda_results_status_09691a_idx')],
                'unique_together': {('dataset', 'version')},
            },
        ),
    ]
