# Generated by Django 6.0 on 2025-12-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edaresult',
            name='cache_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Cache key based on dataset file hash', max_length=64),
        ),
    ]
