# Generated by Django 5.2.9 on 2025-12-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eda", "0002_add_cache_key_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="edaresult",
            name="associations",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="edaresult",
            name="data_quality_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="edaresult",
            name="datetime_analysis",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="edaresult",
            name="text_analysis",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
