# Generated by Django 5.2.9 on 2025-12-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eda', '0003_add_enhanced_analysis_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='edaresult',
            name='global_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='edaresult',
            name='target_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
