# Generated by Django 5.2.9 on 2025-12-11 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_add_sharing_and_comparison_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="report",
            new_name="reports_rep_share_t_9bc35c_idx",
            old_name="reports_rep_share_t_idx",
        ),
    ]
