# Generated by Django 6.0 on 2025-12-07 23:08

import apps.ml.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Algorithm name (e.g., random_forest)', max_length=100)),
                ('display_name', models.CharField(max_length=255)),
                ('algorithm_type', models.CharField(choices=[('logistic_regression', 'Logistic Regression'), ('linear_regression', 'Linear Regression'), ('random_forest', 'Random Forest'), ('gradient_boosting', 'Gradient Boosting')], max_length=50)),
                ('task_type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression')], max_length=20)),
                ('feature_columns', models.JSONField(default=list)),
                ('target_column', models.CharField(max_length=255)),
                ('input_schema', models.JSONField(default=dict, help_text='Expected input schema for predictions')),
                ('preprocessing_params', models.JSONField(default=dict, help_text='Preprocessing configuration (encoders, scalers)')),
                ('metrics', models.JSONField(default=dict, help_text='Evaluation metrics (accuracy, f1, rmse, etc.)')),
                ('feature_importance', models.JSONField(default=dict, help_text='Feature importance scores')),
                ('cross_val_scores', models.JSONField(default=list, help_text='Cross-validation scores')),
                ('hyperparameters', models.JSONField(default=dict, help_text='Model hyperparameters')),
                ('model_file', models.FileField(blank=True, null=True, upload_to=apps.ml.models.model_upload_path)),
                ('model_size', models.PositiveIntegerField(blank=True, help_text='Model file size in bytes', null=True)),
                ('is_best', models.BooleanField(default=False, help_text='Whether this is the best model for its training job')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trained_models', to='datasets.dataset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trained_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trained_models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_column', models.CharField(max_length=255)),
                ('feature_columns', models.JSONField(default=list, help_text='List of feature column names')),
                ('task_type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression')], max_length=20)),
                ('task_type_auto_detected', models.BooleanField(default=True, help_text='Whether task type was auto-detected')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress', models.FloatField(default=0.0, help_text='Progress percentage (0-100)')),
                ('current_step', models.CharField(blank=True, default='', max_length=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('best_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by_jobs', to='ml.trainedmodel')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to='datasets.dataset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'training_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='training_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ml.trainingjob'),
        ),
        migrations.AddIndex(
            model_name='trainingjob',
            index=models.Index(fields=['owner', '-created_at'], name='training_jo_owner_i_ca42b6_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingjob',
            index=models.Index(fields=['status'], name='training_jo_status_20fc5c_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingjob',
            index=models.Index(fields=['dataset'], name='training_jo_dataset_9f8853_idx'),
        ),
        migrations.AddIndex(
            model_name='trainedmodel',
            index=models.Index(fields=['owner', '-created_at'], name='trained_mod_owner_i_1ffb86_idx'),
        ),
        migrations.AddIndex(
            model_name='trainedmodel',
            index=models.Index(fields=['training_job'], name='trained_mod_trainin_b48318_idx'),
        ),
        migrations.AddIndex(
            model_name='trainedmodel',
            index=models.Index(fields=['is_best'], name='trained_mod_is_best_0dc530_idx'),
        ),
    ]
