# Generated by Django 6.0 on 2025-12-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedmodel',
            name='algorithm_type',
            field=models.CharField(choices=[('logistic_regression', 'Logistic Regression'), ('linear_regression', 'Linear Regression'), ('random_forest', 'Random Forest'), ('gradient_boosting', 'Gradient Boosting'), ('svm', 'Support Vector Machine')], max_length=50),
        ),
    ]
