# Generated by Django 6.0 on 2025-12-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_add_svm_algorithm_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='shap_values',
            field=models.JSONField(blank=True, default=dict, help_text='SHAP-based feature importance and explanations'),
        ),
    ]
